<a href="https://colab.research.google.com/github/mastic-choi/FinNLP-Contrarian/blob/main/FinNLP_Contrarian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#필요한 패키지? import
import pandas as pd
import os

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("dyutidasmahaptra/s-and-p-500-with-financial-news-headlines-20082024")

print("Path to dataset files:", path)
#캐글에 있는 데이터 받아오기

Downloading from https://www.kaggle.com/api/v1/datasets/download/dyutidasmahaptra/s-and-p-500-with-financial-news-headlines-20082024?dataset_version_number=1...

100%|██████████| 498k/498k [00:00<00:00, 43.1MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/dyutidasmahaptra/s-and-p-500-with-financial-news-headlines-20082024/versions/1

In [3]:
file_list = os.listdir(path) #경로 받기
filename = file_list[0]      #파일 이름받기
full_path = os.path.join(path, filename) #경로이름+파일이름
df = pd.read_csv(full_path)
display(df.head())

                                               Title        Date       CP
0   JPMorgan Predicts 2008 Will Be "Nothing But Net"  2008-01-02  1447.16
1  Dow Tallies Biggest First-session-of-year Poin...  2008-01-02  1447.16
2                   2008 predictions for the S&P 500  2008-01-02  1447.16
3  U.S. Stocks Higher After Economic Data, Monsan...  2008-01-03  1447.16
4  U.S. Stocks Climb As Hopes Increase For More F...  2008-01-07  1416.18

In [4]:
#원본 데이터를 보존하기 위해 분석용 데이터 생성
df_train = df.copy()

**데이터셋 설명**:
글로벌 금융위기부터 최근 AI 랠리까지 약 16년 간의 S&P 500 지수와 주요 경제 뉴스를 포함한 시계열 데이터입니다.

### Case 1 : 뉴스 헤드라인의 감성 분석을 위해 **VADER** 모델을 활용합니다.
처리 Flow
1. 각 날짜별로 존재하는 복수의 뉴스 헤드라인(예: 3개)에 대해 각각 VADER 감성 점수(Compound Score)를 산출합니다.
2. 동일 날짜의 뉴스 점수들을 **평균(Mean)** 내어, 해당 일자의 대표 **'시장 심리 지수'**를 생성합니다.
3. 산출된 일별 평균 점수를 AI 모델의 학습 피처(Feature)로 사용합니다.

VaderSentiment(https://github.com/cjhutto/vaderSentiment?tab=readme-ov-file#python-demo-and-code-examples)

In [5]:
#Vader 다운받기
!pip install vaderSentiment

Collecting vaderSentiment
  Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl.metadata (572 bytes)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from vaderSentiment) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2025.10.5)
Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl (125 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.0/126.0 kB 2.9 MB/s eta 0:00:00
Installing collected packages: vaderSentiment
Successfully installed vaderSentiment-3.3.2

In [6]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
a = 0
analyzer = SentimentIntensityAnalyzer()
for i in df_train['Title']: # df_train 속 제목을 한 행씩 i로 넣어서 보냄
    vs = analyzer.polarity_scores(i)
    print("{:-<65} {}".format(i, str(vs)))

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
Leon Cooperman Predicts Percentage S&P 500 Will Fall Before It Turns Around {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Stock Market News for Feb 28, 2023------------------------------- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
US Markets End Down for the Day and Month------------------------ {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Goldman expects STOXX Europe 600 and TOPIX to outperform S&P 500 in 2023 {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
S&P 500 index is 2.5 times too expensive: JPMorgan--------------- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Tesla, tech and travel stocks have ginormous gains this year----- {'neg': 0.0, 'neu': 0.789, 'pos': 0.211, 'compound': 0.34}
Billionaire Leon Cooperman Expects US Recession, 22% Plunge in S&P 500 {'neg': 0.219, 'neu': 0.781, 'pos': 0.0, 'compound': -0.4215}
Dow closes more than 200 points lower Tuesday, major averages end February with losses: Live updates {'neg': 0.259, 'neu': 0.741, 'pos': 0.0, 'compound': -0.5994}
Stock Market Today: Dow, S&P Live Updates for March 1------------ {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
S&P 500 Mixed as 10-Year Treasury Note Yield Hits Highest Level Since Nov. 10 {'neg': 0.0, 'neu': 0.878, 'pos': 0.122, 'compound': 0.2023}
Wall Street closes out weak February as Fed concerns remain------ {'neg': 0.244, 'neu': 0.756, 'pos': 0.0, 'compound': -0.4404}
How To Invest In Structured Notes – Forbes Advisor--------------- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
The Single Most Terrifying Number in Berkshire Hathaway's Latest Results {'neg': 0.294, 'neu': 0.589, 'pos': 0.116, 'compound': -0.5291}
Where Is the Stock Market Heading? March 2023 Forecast----------- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Morgan Stanley's Wilson: S&P 500 Could Fall About 20%------------ {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
S&P, Nasdaq weak as manufacturing stokes Fed concerns------------ {'neg': 0.293, 'neu': 0.707, 'pos': 0.0, 'compound': -0.4404}
Market Outlook: 3 Reasons Long-Term Investors Should Be Optimistic {'neg': 0.0, 'neu': 0.777, 'pos': 0.223, 'compound': 0.3182}
Market gets a reality check | E*TRADE Monthly Market Commentary-- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Is Big Tech's Dominance Over?------------------------------------ {'neg': 0.0, 'neu': 0.69, 'pos': 0.31, 'compound': 0.2023}
SPY: Investors: Beware the Ides of March!------------------------ {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
US Markets Begin the Month Mixed on Familiar Concerns------------ {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Apple Is Still The Richest Company — By Squatting On Your Money-- {'neg': 0.0, 'neu': 0.764, 'pos': 0.236, 'compound': 0.5267}
The Recession Debate Pits CEOs and Economists Against Equity Analysts and Investors {'neg': 0.203, 'neu': 0.797, 'pos': 0.0, 'compound': -0.4215}
First Solar Reports Smaller-Than-Expected Loss, Upbeat Guidance-- {'neg': 0.277, 'neu': 0.723, 'pos': 0.0, 'compound': -0.3182}
ISM Manufacturing PMI Misses Expectations, S&P 500 Tests New Lows {'neg': 0.316, 'neu': 0.684, 'pos': 0.0, 'compound': -0.4019}
S&P 500 sheds 2.6% in February as inflation, interest rate worries persist {'neg': 0.177, 'neu': 0.633, 'pos': 0.19, 'compound': 0.0516}
Corporate America's Earnings Quality Is the Worst in Three Decades {'neg': 0.313, 'neu': 0.687, 'pos': 0.0, 'compound': -0.6249}
PE Has Outperformed Stocks for Decades — And Especially During High Inflation {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Can You Become a Millionaire With Only S&P 500 Index Funds?------ {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Sector Views: Tech Talk – Global X ETFs-------------------------- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Stock market news today: S&P 500, Nasdaq fall, yields rise after hawkish Fedspeak {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Stock Market Today: Dow, S&P Live Updates for March 2------------ {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
S&P 500 and Nasdaq 100 attempt to build higher as latest data gives traders some confidence {'neg': 0.0, 'neu': 0.82, 'pos': 0.18, 'compound': 0.5106}
Record Number Of Black CEOs Will Run S&P 500 Companies----------- {'neg': 0.0, 'neu': 0.874, 'pos': 0.126, 'compound': 0.0772}
S&P 500 and Nasdaq close lower to begin March as the 10-year Treasury yield touches 4%: Live updates {'neg': 0.11, 'neu': 0.8, 'pos': 0.09, 'compound': -0.1027}
Apple Stock: Is March A Good Month To Invest?-------------------- {'neg': 0.0, 'neu': 0.734, 'pos': 0.266, 'compound': 0.4404}
Chris Womack To Join 'Record Number' Of 8 Total Black Executives Leading S&P 500 Companies {'neg': 0.0, 'neu': 0.788, 'pos': 0.212, 'compound': 0.3612}
DBMF's Returns Track Record Beats SPY---------------------------- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
15 Companies that Just Started Paying Dividends------------------ {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Technical Indicator Signals the End of the 2022 Bear Market------ {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Nvidia Climbs Into The Top Five S&P 500 Weightings--------------- {'neg': 0.0, 'neu': 0.816, 'pos': 0.184, 'compound': 0.2023}
Earnings Insight Infographic: Q4 2022 By the Numbers------------- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Should You Still Invest if a Recession Is Coming? Here's What History Says {'neg': 0.189, 'neu': 0.811, 'pos': 0.0, 'compound': -0.4215}
US Markets Pick Up Steam in the Afternoon and Post Gains--------- {'neg': 0.0, 'neu': 0.806, 'pos': 0.194, 'compound': 0.34}
Stocks on the move: Tesla's and Hormel's drop, while Salesforce, Macy's and Kroger shares surge {'neg': 0.121, 'neu': 0.751, 'pos': 0.127, 'compound': 0.0258}
Stock market news today: Stocks rally as Salesforce's 11% gain lifts Dow while S&P, Nasdaq reverse early losses {'neg': 0.122, 'neu': 0.724, 'pos': 0.154, 'compound': 0.1779}
What Is The Shiller P/E Ratio?----------------------------------- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Stocks gain as Bostic backs quarter-point hike------------------- {'neg': 0.125, 'neu': 0.521, 'pos': 0.354, 'compound': 0.4939}
NASDAQ Index, S&P 500, Dow Jones Analysis – NASDAQ Climbs Back, Dow Jones Supported By Salesforce Performance {'neg': 0.0, 'neu': 0.874, 'pos': 0.126, 'compound': 0.3182}
Stocks close higher, Dow gains 300 points as Fed’s Bostic spurs relief rally: Live updates {'neg': 0.0, 'neu': 0.703, 'pos': 0.297, 'compound': 0.6705}
Stock Market Today: Dow, S&P Live Updates for March 3------------ {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
What It Will Take For Tesla To Be Worth $1 Trillion Again-------- {'neg': 0.0, 'neu': 0.853, 'pos': 0.147, 'compound': 0.2263}
Almost all S&P 500 companies reported earnings. The results aren’t great {'neg': 0.0, 'neu': 0.709, 'pos': 0.291, 'compound': 0.6249}
Troy Cates Talks Income and Yield for CSHI and SPYI on ETF IQ---- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Is It Time To Reassess Your Focus On Large-Cap Stocks? | Chase--- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Why the 200-Day Moving Average Matters in Today’s Market--------- {'neg': 0.0, 'neu': 0.879, 'pos': 0.121, 'compound': 0.0258}
Sharp drop in equity premium may mark return of 60/40 portfolio-- {'neg': 0.174, 'neu': 0.826, 'pos': 0.0, 'compound': -0.2732}
Richest Companies 2023 (Companies with the Most Cash)------------ {'neg': 0.0, 'neu': 0.673, 'pos': 0.327, 'compound': 0.5267}
Stock Market Today: S&P 500 Snaps Weekly Losing Streak----------- {'neg': 0.245, 'neu': 0.755, 'pos': 0.0, 'compound': -0.3818}
Markets Jump on the Day and Week on Rate Optimism---------------- {'neg': 0.0, 'neu': 0.72, 'pos': 0.28, 'compound': 0.5423}
12 'Dirt Cheap' Stocks Are Due For A Rally, Analysts Say--------- {'neg': 0.194, 'neu': 0.806, 'pos': 0.0, 'compound': -0.34}
Big Tech's $200 Billion Surge Leads Stock Market Rally—But Rate-Fueled Optimism May Be Fleeting {'neg': 0.0, 'neu': 0.788, 'pos': 0.212, 'compound': 0.5423}
S&P 500 Annual Returns------------------------------------------- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Stock Traders Are Ignoring Blaring Bond Alarms------------------- {'neg': 0.49, 'neu': 0.51, 'pos': 0.0, 'compound': -0.5859}
Stocks close higher Friday, Dow breaks 4-week losing streak as 10-year Treasury yield retreats: Live updates {'neg': 0.141, 'neu': 0.761, 'pos': 0.098, 'compound': -0.2023}
Larger Cuts Than Average to EPS Estimates for S&P 500 Companies for Q1 To Date {'neg': 0.136, 'neu': 0.864, 'pos': 0.0, 'compound': -0.296}
Numbers dive: Warren Buffett's performance is even more amazing than you think. {'neg': 0.0, 'neu': 0.729, 'pos': 0.271, 'compound': 0.624}
Morgan Stanley's Mike Wilson: S&P 500 could drop 20%------------- {'neg': 0.208, 'neu': 0.792, 'pos': 0.0, 'compound': -0.2732}
Will March be a good month for the Dow, S&P 500, Nasdaq 100 and Russell 2000? {'neg': 0.0, 'neu': 0.838, 'pos': 0.162, 'compound': 0.4404}
Stock market news today: Stocks gain, 10-year yield falls back below 4% {'neg': 0.0, 'neu': 0.764, 'pos': 0.236, 'compound': 0.5267}
14 S&P 500 Stocks To Switch Sectors In March - ETF Focus on TheStreet: ETF research and Trade Ideas {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
This S&P 500 Stock has Outperformed Tesla in 2023---------------- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Morgan Stanley's bearish top strategist says stocks could keep rising—in the short term {'neg': 0.0, 'neu': 0.87, 'pos': 0.13, 'compound': 0.2023}
Stock Market News for Mar 6, 2023-------------------------------- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
America’s credit rating could get downgraded even if a default is avoided, Fitch Ratings warns {'neg': 0.207, 'neu': 0.652, 'pos': 0.141, 'compound': -0.0516}
10 S&P 500 Stocks Are Practically Immune To More Fed Rate Hikes-- {'neg': 0.0, 'neu': 0.833, 'pos': 0.167, 'compound': 0.296}
Wish You'd Bought at the Bottom? Here's Why It's Not That Important. {'neg': 0.111, 'neu': 0.7, 'pos': 0.189, 'compound': 0.2751}
Growth ETFs Diverge Significantly After S&P Rebalance------------ {'neg': 0.0, 'neu': 0.698, 'pos': 0.302, 'compound': 0.3818}
14 Best Consumer Staples Dividend Stocks To Buy Now-------------- {'neg': 0.0, 'neu': 0.656, 'pos': 0.344, 'compound': 0.6369}
GICS Changes Will Affect Big Fintech ETF------------------------- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
This 11.8%-Yielding ETF Pays Large Monthly Dividends------------- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Growth ETFs Diverge Significantly After S&P Rebalance------------ {'neg': 0.0, 'neu': 0.698, 'pos': 0.302, 'compound': 0.3818}
Mind the Gap: Rarity of Women in Top Roles Means Gender Pay Gap Remains Wide {'neg': 0.086, 'neu': 0.802, 'pos': 0.111, 'compound': 0.1027}
Best And Worst S&P Sectors Over The Last 12 Months--------------- {'neg': 0.252, 'neu': 0.491, 'pos': 0.258, 'compound': 0.0258}
Unisys, Bed Bath & Beyond slide after removal from small-cap index {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Markets Little Changed Ahead of Powell Testimony----------------- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
How Does Inflation Affect The Stock Market? – Forbes Advisor----- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Stock Market Today: Dow, S&P Live Updates for March 7------------ {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Dow closes higher Monday to notch four-day win streak: Live updates {'neg': 0.0, 'neu': 0.725, 'pos': 0.275, 'compound': 0.5859}
0DTE options could turn 5% intraday market decline into 25% rout -JPMorgan {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Morgan Stanley Sees Near-Term US Stock Market Rally-------------- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Daily Update March 6, 2023--------------------------------------- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
S&P 500 ekes out gain, Treasury yields turn higher on eve of Powell testimony {'neg': 0.0, 'neu': 0.698, 'pos': 0.302, 'compound': 0.6369}
S&P 500 Forecast: SPX to capitalize on bullish chart structure this week {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Dow, S&P 500 gains belie bad market breadth---------------------- {'neg': 0.294, 'neu': 0.504, 'pos': 0.202, 'compound': -0.2732}
WidePoint Signs Mobile and Telecom Managed Services Contract with S&P 500 Food & Beverage Company {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Stock market news today: Stocks pare gains, finish mixed to start busy week {'neg': 0.0, 'neu': 0.833, 'pos': 0.167, 'compound': 0.34}
Growth stock vs. value stock? It's all in the eye of the beholder {'neg': 0.0, 'neu': 0.688, 'pos': 0.312, 'compound': 0.6124}
S&P 500 ends slightly higher ahead of Powell testimony, upcoming data {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
PwC and KPMG fall behind in promoting women to run major audit work {'neg': 0.0, 'neu': 0.828, 'pos': 0.172, 'compound': 0.3612}
Bitcoin Outperforms NASDAQ, S&P 500, Dow Jones, and Gold Combined {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Investors Cash In On 12 'Triple Play' Stocks That Do No Wrong---- {'neg': 0.0, 'neu': 0.669, 'pos': 0.331, 'compound': 0.6065}
Europe Stocks Outperforming US Equities Is Set to Fade, Says BlackRock {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Before the Bell: Change in the S&P 500, Rivian to Issue More Debt {'neg': 0.189, 'neu': 0.811, 'pos': 0.0, 'compound': -0.4201}
Active vs Passive Investing: Even in Bear Market, Active Struggled to Outperform {'neg': 0.136, 'neu': 0.455, 'pos': 0.409, 'compound': 0.5859}
Gain Small-Cap Exposure with Options on the Russell 2000 Index--- {'neg': 0.0, 'neu': 0.726, 'pos': 0.274, 'compound': 0.5267}
'Slim majority' of actively-managed U.S. large-cap equity mutual funds fail to beat S&P 500 in 2022 {'neg': 0.189, 'neu': 0.811, 'pos': 0.0, 'compound': -0.5423}
Most stock pickers underperformed in 2022's stock picker's market {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Yeah, about that active comeback . . .--------------------------- {'neg': 0.0, 'neu': 0.55, 'pos': 0.45, 'compound': 0.5994}
5 Major Reasons Tech Stocks Will Soar in 2023-------------------- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Stock market news today: Stocks sink after Powell tells Congress rates could go 'higher' {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Dow, S&P 500 book worst day in 2 weeks as Powell's hawkish tone sparks concerns over higher interest rates {'neg': 0.17, 'neu': 0.705, 'pos': 0.124, 'compound': -0.2732}
Motilal Oswal Mutual Fund restricts fresh investments in 3 international funds from March 10 {'neg': 0.139, 'neu': 0.723, 'pos': 0.139, 'compound': 0.0}
Stock Market Today: Dow, S&P Live Updates for March 8------------ {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
S&P 500 Information Technology sector's historically strong performance {'neg': 0.0, 'neu': 0.68, 'pos': 0.32, 'compound': 0.5106}
Stocks close sharply down after Powell says rates will rise more than expected {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Wall Street falls more than 1% as Powell flags sharper rate hikes {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
How to Identify a Stock Market Bottom? Look for These Signals---- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Dow drops 574 points as Jerome Powell rate hike comments sting--- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
‘Slim majority’ of actively-managed U.S. large-cap equity mutual funds fail to beat S&P 500 in 2022 {'neg': 0.189, 'neu': 0.811, 'pos': 0.0, 'compound': -0.5423}
Growth and value ETFs' performance diverge after S&P rebalance--- {'neg': 0.0, 'neu': 0.583, 'pos': 0.417, 'compound': 0.6124}
S&P 500 CEO Compensation Increase Trends------------------------- {'neg': 0.0, 'neu': 0.685, 'pos': 0.315, 'compound': 0.3182}
Bear Trap? Market Holds Critical Support------------------------- {'neg': 0.447, 'neu': 0.291, 'pos': 0.262, 'compound': -0.2263}
Stock market news today: Stocks finish mixed as Powell wraps up testimony amid continued jobs strength {'neg': 0.0, 'neu': 0.824, 'pos': 0.176, 'compound': 0.4939}
3 investment strategies that outperform the market (2023)-------- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Stock Market News for Mar 8, 2023-------------------------------- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Wall Street eases, investors step back after Fitch US rating cut- {'neg': 0.157, 'neu': 0.672, 'pos': 0.172, 'compound': 0.0516}
Here's What Happens When a Stock is Removed from an Index-------- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Terry Smith: Why You Should Stay Invested In The Stock Market---- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Is It Really Safe to Invest in the S&P 500 Right Now? Here's What History Says {'neg': 0.0, 'neu': 0.824, 'pos': 0.176, 'compound': 0.4927}
Stocks close mixed after Powell's testimony and fresh jobs data-- {'neg': 0.0, 'neu': 0.796, 'pos': 0.204, 'compound': 0.3182}
Prediction: The S&P 500 and Nasdaq Will Be Up in 2023------------ {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
What Is Volmageddon? Why Record Options Trading Could Risk Another 20% Stock Crash {'neg': 0.304, 'neu': 0.696, 'pos': 0.0, 'compound': -0.5859}
Fund of Women-Run Firms Is Beating the S&P 500 Since Launching--- {'neg': 0.231, 'neu': 0.769, 'pos': 0.0, 'compound': -0.4588}
Here's What Happens When a Stock is Removed from an Index-------- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Stock Market Today: Dow, S&P Live Updates for March 9------------ {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Short sellers pare back bets as US equities rally---------------- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
S&P 500 barely gains as investors eye upcoming jobs data, rate hikes {'neg': 0.0, 'neu': 0.839, 'pos': 0.161, 'compound': 0.2748}
The Next Bull Market Is Coming: 2 Strong Index Funds to Buy Now and Hold Forever {'neg': 0.0, 'neu': 0.82, 'pos': 0.18, 'compound': 0.5106}
3 Top Guru Favorites Trading Near 52-Week Lows------------------- {'neg': 0.158, 'neu': 0.439, 'pos': 0.404, 'compound': 0.4215}
2 Key Facts Every Investor Needs to Know About S&P 500 Drawdowns- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Cboe Plays Down Danger From Zero-Day Options After Trading Boom-- {'neg': 0.254, 'neu': 0.597, 'pos': 0.149, 'compound': -0.34}
GICS changes set to impact S&P 500 and sector ETFs--------------- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Stock Market News for Mar 9, 2023-------------------------------- {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Izzy Englander and the New Rules of Hedge Funds------------------ {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
The Semiconductor Industry is Showing Relative Strength: 2 Stocks to Join the Rally {'neg': 0.0, 'neu': 0.671, 'pos': 0.329, 'compound': 0.6597}
15 Best Stocks Under $100---------------------------------------- {'neg': 0.0, 'neu': 0.488, 'pos': 0.512, 'compound': 0.6369}
Investment in Rolex, Patek watches exceeds S&P gains over five years: report {'neg': 0.0, 'neu': 0.821, 'pos': 0.179, 'compound': 0.34}
Is It Historically Wise To Invest in the S&P 500 as Market Continues Volatile Streak? {'neg': 0.0, 'neu': 0.819, 'pos': 0.181, 'compound': 0.4767}
Rolex and Patek Philippe investments beat S&P gains since 2018--- {'neg': 0.0, 'neu': 0.789, 'pos': 0.211, 'compound': 0.34}
Markets Sink on Interest Rate, Banking Worries------------------- {'neg': 0.259, 'neu': 0.463, 'pos': 0.278, 'compound': 0.0516}
Markets close sharply lower as bank stocks take a beating-------- {'neg': 0.394, 'neu': 0.606, 'pos': 0.0, 'compound': -0.6369}

In [7]:
coumpound_score = [] # 분석 결과값이 저장될 빈 리스트
for i in df_train['Title']: # df_train 속 제목을 한 행씩 i로 넣어서 보냄
    vs = analyzer.polarity_scores(i) # 감성분석 실시
    coumpound_score.append(vs['compound']) #리스트에 넣기
df_train['vader_coumpound'] = coumpound_score
df_train.head()

,Title,Date,CP,vader_coumpound
0,"JPMorgan Predicts 2008 Will Be ""Nothing But Net""",2008-01-02,1447.16,0.0000
1,Dow Tallies Biggest First-session-of-year Poin...,2008-01-02,1447.16,-0.2732
2,2008 predictions for the S&P 500,2008-01-02,1447.16,0.0000
3,"U.S. Stocks Higher After Economic Data, Monsan...",2008-01-03,1447.16,0.0000
4,U.S. Stocks Climb As Hopes Increase For More F...,2008-01-07,1416.18,0.6249

일반적인 소셜 미디어 감성 분석 모델인 **VADER**를 사용하여 S&P 500 금융 뉴스 헤드라인의 감성을 분석한 결과.
명백한 시장 등락(Sink, Tank, Plunge, Higher)을 나타내는 헤드라인 상당수가 **중립**으로 분류됨.
금융 시장에서 'Tank(폭락하다)', 'Sink(가라앉다)', 'Correction(조정)'은 강력한 방향성을 갖지만, 일반 영어 사전에서는 단순한 물리적 움직임이나 중립적 단어로 인식될것으로 예측됨.

In [8]:
df_train.head()

,Title,Date,CP,vader_coumpound
0,"JPMorgan Predicts 2008 Will Be ""Nothing But Net""",2008-01-02,1447.16,0.0000
1,Dow Tallies Biggest First-session-of-year Poin...,2008-01-02,1447.16,-0.2732
2,2008 predictions for the S&P 500,2008-01-02,1447.16,0.0000
3,"U.S. Stocks Higher After Economic Data, Monsan...",2008-01-03,1447.16,0.0000
4,U.S. Stocks Climb As Hopes Increase For More F...,2008-01-07,1416.18,0.6249